module.exports = {
  // DEBUG
  SHOW_SPAWN_RECT: false,
  INVINCIBLE_PLAYERS: false,
  
  // GAME CONTROL
  MAX_OBJECTIVES_AT_ONCE: 6,
  PLAYGROUND_WIDTH: 1920,
  PLAYGROUND_HEIGHT: 1080,
  OBJECTIVE_SCORE: 1, // 1,
  SAFE_ZONE_SIZE: 50,
  
  // SERVER CONTROL
  FPMS: 1000 / 40,
}